# Generated by Django 5.0.2 on 2024-03-24 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0002_persona_remove_curso_docente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='docente_a_cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academia.docente'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='curso_a_cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academia.curso'),
        ),
    ]
