# Generated by Django 5.0.2 on 2024-04-05 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0003_alter_curso_docente_a_cargo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='tipo',
            field=models.CharField(choices=[('1', 'Diplomatura'), ('2', 'Tecnicatura'), ('3', 'Licenciatura'), ('4', 'Ingenieria'), ('5', 'Master'), ('6', 'Doctorado')], default='F', max_length=1),
        ),
    ]
